### ISSUE TITLE
missing render and resize events

### ISSUE THREAD

**Issue by timelyportfolio** [BigFatDog/parcoords-es#1]
Thank you so much for converting this!  I discovered that `render` and `resize` events are no longer exposed as they were before (see [lines](https://github.com/syntagmatic/parallel-coordinates/blob/master/src/events.js#L1)).  Was this intentional?

**Comment by BigFatDog** [comment]
Thank you for your input! This is a bug with event dispatching with my code.
version 1.0.1 has been released with bug fixes

**Comment by timelyportfolio** [comment]
I just realized I never said thank you.  Thank you so much!  I plan to re-invigorate my efforts incorporating d3v4, so I will report back with anything else I find.  I really, really appreciate your efforts on this conversion.

**Comment by BigFatDog** [comment]
You're welcome. I'm happy that you find my works useful and inspiring.  Your appreciation encourages me, too.
I've completely upgraded my visualizations to d3 v4 after experiencing some failures. Now I feel i'm on the right track.

Keep enjoying v4!
