### ISSUE TITLE
updateAxes() broken?

### ISSUE THREAD

**Issue by joshhjacobson** [BigFatDog/parcoords-es#15]
When using the `updateAxes` function, I get the following error: _TypeError: node is null_

For a reproducible example, I've added it to brushing.html:

```javascript
// load csv file and create the chart
        d3.csv('data/cars.csv').then(function(data) {
            parcoords
                .data(data)
                .hideAxis(["name"])
                .composite("darker")
                .render()
                .shadows()
                .reorderable()
                .brushMode("1D-axes")  // enable brushing
                .on("brushend", function(brushed) {

                  parcoords.updateAxes();

                });
        });
```

Any insight would be appreciated!

**Comment by BigFatDog** [comment]
Confirmed a bug. Version 2.1.0 has been released with the bug-fix

`updateAxes` should be used after changing dimension orders, other than in `brushend` events. (Brushing on a dimension doesn't change its corresponding axis. furthermore, `updateAxes()` will brush chart again, which will result in triggering `brushend` event infinitely)

**Comment by BigFatDog** [comment]
[v2.1.1](https://github.com/BigFatDog/parcoords-es/releases/tag/v2.1.1) has been released with the bug-fix.

**Comment by joshhjacobson** [comment]
Thanks! This seems to have handled all the console errors, and axis reordering is _mostly_ functional. While testing, I noticed a bug where the right-most axis seems to become disconnected from the canvas. You can still interact with all the other axes by dragging them around and brushing, but the right-most one is unresponsive. If you drag another axis toward it, the polylines will adjust accordingly, but the svg axis itself will remain fixed. 

<img width="517" alt="show" src="https://user-images.githubusercontent.com/23021614/41616752-fbfa2c5a-73bb-11e8-88dc-34f4f7bb5c9c.png">

This was produced using the example above where I start with one axis hidden, and then click the button to 'show' it.

**Comment by BigFatDog** [comment]
You're welcome. 
The above problem is a bug. I observe that when a hidden axis is revealed, it cannot be dragged or brushed.

**Comment by timelyportfolio** [comment]
@BigFatDog, not sure if this is related or should be a separate issue, but on reorder of axes (reproducible [example](https://beta.observablehq.com/@timelyportfolio/simple-example-from-parcoord-es)), I get

![image](https://user-images.githubusercontent.com/837910/41851531-ce11d554-784d-11e8-9422-f4b2fe62a4c4.png)

**Comment by BigFatDog** [comment]
@timelyportfolio  #27 is opened to track this bug.

Your words on observable link are warm and inspiring. Those words let me recall your article that I read long ago: "Time isn't money" -- I feel strongly that my time that are contributed to open-source are valued and my efforts are respected.

Thank you a lot for your kindness and understanding. All the best!

Yun

**Comment by BigFatDog** [comment]
@joshhjacobson 's issue is tracked in #26 
@timelyportfolio 's issue is tracked in #27

**Comment by timelyportfolio** [comment]
Very appreciative of your work @BigFatDog and very likely will be in position to contribute over the next couple of months.  Thanks so much!
