### ISSUE TITLE
Axes configuration

### ISSUE THREAD

**Issue by joshhjacobson** [BigFatDog/parcoords-es#16]
`pc.scale(input_axis, [lower, upper])` successfully adjusts the yscale domain and ticks of an axis, but the axis itself is the only thing affected -- the polylines are not adjusted. How would I go about updating the plot to match the new axis domain? 

I'm guessing it has something to do with `pc.applyAxisConfig()` but I'm unsure what the correct parameters should be. Thanks for the help!

**Comment by BigFatDog** [comment]
I've tested this api and usage should be:
```
pc.scale(input_axis, [lower, upper]);
pc.data(pc.data().filter(d => d[input_axis] >= lower && d[input_axis] <= upper));
pc.render();
```
I can filter data accordingly when `pc.scale` is called, but I tend to not do this because it is end user who should control data via `pc.data`. If I filter data with `pc.scale`, end user will lose the track of what the current data is.

What do you think?

**Comment by joshhjacobson** [comment]
I agree that `pc.scale` should not manipulate the data; that should be left to `pc.data`. Actually, my goal should not even require the data to be filtered. I want to expand the axis and have the data re-mapped so that the range appears more consolidated. I think the code should look something like this:


```javascript
 var input = "weight (lb)";
 var upper = 10000;
 var lower = 0;

 pc.scale(input,[lower, upper]);
 pc.updateAxes();    // or pc.applyAxisConfig(input)
 pc.render();
```

But what I get is simply:
<img width="112" alt="before" src="https://user-images.githubusercontent.com/23021614/41502555-daeba03c-7179-11e8-8da6-f86feb221fa6.png">
<img width="112" alt="after" src="https://user-images.githubusercontent.com/23021614/41502557-e0737c50-7179-11e8-83ad-3969add5c56a.png">

The svg ticks have been updated, but the data is still mapped to the same place. Is there already a way to fix this?

Side note: I think it would also be useful if `pc.scale` allowed the user to specify the type of scale to use for the axis (log, linear, ordinal, custom). Perhaps `pc.scale(input, [lower, upper], scale)`? Maybe this is too much?

**Comment by BigFatDog** [comment]
[v2.1.1](https://github.com/BigFatDog/parcoords-es/releases/tag/v2.1.1) has been released with the bug-fix.

**Comment by joshhjacobson** [comment]
I've tested your new set-scale example in the demos folder, and while the polylines are now rendered to the correct location on the axis, the call to `pc.scale('year', [30, 90])` breaks with _TypeError: pc.render().default is not a function, scale.js:4:4_ .

Thus, the axis ticks are not updated:
<img width="60" alt="scale" src="https://user-images.githubusercontent.com/23021614/41619914-428b15cc-73c5-11e8-9b98-6ea08d4e921a.png">

**Comment by BigFatDog** [comment]
[v2.1.4] has been published with the bug-fix

**Comment by joshhjacobson** [comment]
Looks great! Thank you for your consistent and quality work!

**Comment by BigFatDog** [comment]
Thanks for your appreciation of my work. You've contributed detailed code samples and keen observations to issues, and that help me a lot resolve problems.
