### ISSUE TITLE
NPM install issue

### ISSUE THREAD

**Issue by mutantkeyboard** [BigFatDog/parcoords-es#2]
Hi @BigFatDog 
Thank you one more time for porting this to ES6. 
For some reason when installing from NPM, module name is not `parcoords-es`, but `parcoord-es`, 
so `npm install parcoord-es --save` works, while `npm install parcoords-es --save` doesn't.

**Comment by BigFatDog** [comment]
Hello. 
I'd keep 'parcoord-es'. Readme has been revised accordingly.
Thank you for your input.
