### ISSUE TITLE
ERROR in ./node_modules/parcoord-es/dist/parcoords.mjs 1035:12-17 Can't import the named export 'mouse' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by ciukstar** [BigFatDog/parcoords-es#20]
Hi! I keep getting these errors on '`ng build`' and before renaming the file './node_modules/parcoord-es/dist/parcoords.mjs' to something like './node_modules/parcoord-es/dist/Xparcoords.mjsX'. I use Angular 6. As I understand, there are some problems with webpack and .mjs files. What is the best way to deal with this problem. I keep getting these errors after each '`npm update`' of parcoords-es:

ERROR in ./node_modules/parcoord-es/dist/parcoords.mjs
1035:12-17 Can't import the named export 'mouse' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/parcoord-es/dist/parcoords.mjs
103:29-35 Can't import the named export 'select' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/parcoord-es/dist/parcoords.mjs
1090:16-20 Can't import the named export 'drag' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/parcoord-es/dist/parcoords.mjs
1285:14-18 Can't import the named export 'drag' from non EcmaScript module (only default export is available)
.....
.....

**Comment by BigFatDog** [comment]
Hello. Would you please provide more information about your environment?
* Webpack version
* webpack config
* Sample code

Will there be any problem if you keep `.mjs` file unchanged?

**Comment by bfischer1121** [comment]
Get the same error with unejected CRA 2.x (react-scripts@2.0.0-next.3e165448) on webpack 4.8.3
```javascript
import 'parcoord-es/parcoords.css';
import ParCoords from 'parcoord-es';
//...
let pc = ParCoords({ nullValueSeparator: 'bottom' })(chart.ref.current);
```

**Comment by bfischer1121** [comment]
Relevant issues: webpack/webpack#6699 and apollographql/react-apollo#1737

Changing `parcoords.mjs` to `parcoords.esm.js` avoided the issue, but I opted for this for the time being:
```javascript
import 'parcoord-es/dist/parcoords.css';
import ParCoords from 'parcoord-es/dist/parcoords.js';
//...
let pc = ParCoords({ nullValueSeparator: 'bottom' })(chart.ref.current);
```
(`parcoord-es/parcoords.css` -> `parcoord-es/dist/parcoords.css` too)

Thanks.

**Comment by BigFatDog** [comment]
[v2.1.6](https://github.com/BigFatDog/parcoords-es/releases/tag/v2.1.6) has been published with the bug-fix. I've tested in a webpack 4 project and it works. 

Although the original issue is based on `angular`'s `ng build` but not on `webpack 4`, I think `v2.1.6` should fix the original issue, too. 

If anyone is still using previous versions with `webpack 4`. Please upgrade  `parcoord-es` or consider a workaround that has been introduced by relevant discussions (webpack/webpack#6699 and apollographql/react-apollo#1737, thanks @bfischer1121 for providing it):

Add the following config to your webpack config:
```
{
  type: 'javascript/auto',
  test: /\.mjs$/,
  use: []
}
```

**Comment by ciukstar** [comment]
No more errors on `ng build`. Issue fixed. Thanks!

**Comment by BigFatDog** [comment]
You're welcome. 😃
