### ISSUE TITLE
Two parcoords instances are linked

### ISSUE THREAD

**Issue by BigFatDog** [BigFatDog/parcoords-es#21]
@joshhjacobson mentioned a bug in #14 's follow up:

> Another strange thing happens when working with two ParCoords variables:
```
       var pc1 = ParCoords()("#plot01")
            .alpha(0.4)
        var pc2 = ParCoords()("#plot02")
            .alpha(0.4)

        // load csv file and create the chart
        d3.csv('data/cars.csv').then(function(data) {
            pc1
                .data(data)
                .hideAxis(["name"])
                .composite("darker")
                .render()
                .shadows()
                .reorderable()
                .brushMode("1D-axes")  // enable brushing
                .on("brushend", function(){
                  console.log(pc1.selected());
                  console.log(pc2.selected());
                });

            pc2
                .data(data)
                .hideAxis(["name"])
                .composite("darker")
                .render()
                .shadows()
                .reorderable()
                .brushMode("1D-axes")  // enable brushing
                .on("brushend", function(){
                  console.log(pc1.selected());
                  console.log(pc2.selected());
                });
        });

        d3.select('#brushReset').on('click', function () {
            pc1.brushReset();
            pc2.brushReset();

        });
```
> The two plots seem to be linked, in that console.log(pc1.selected()) and console.log(pc2.selected()) always return the same data even when brushes are different between plots. Could this be because of the way I'm loading the data?

> Interestingly, you must also click the brushReset button twice in order for both plots to refresh.

**Comment by BigFatDog** [comment]
Fixed. [v2.1.2](https://github.com/BigFatDog/parcoords-es/releases/tag/v2.1.2) has been released with bugfix

**Comment by joshhjacobson** [comment]
Looks great! In the example I provided above, the plots are visually independent. Brushing works as expected with no connection between plots and the brush reset button works with one click. 

In the console, I did notice that `pc.selected()` still returns the same data for both plots when brushes are different between plots, but maybe this is part of a different issue now?

**Comment by BigFatDog** [comment]
Let's keep the issue of `pc.selected()` here. I'll schedule another release for the bug-fix

**Comment by BigFatDog** [comment]
[v2.1.3](https://github.com/BigFatDog/parcoords-es/releases/tag/v2.1.3) has been published with the bug-fix

**Comment by joshhjacobson** [comment]
Perfect, it works!
