### ISSUE TITLE
Draw Horizontal line in the PCP chart

### ISSUE THREAD

**Issue by sam140** [BigFatDog/parcoords-es#25]
Is there any way to draw a horizontal line based on some value like we will have a separate Y axis scale then we want draw a horizontal line in the pcp chart.

**Comment by BigFatDog** [comment]
Hi, Would you please elaborate more details on this issue? 
What's PCP chart? It would be great if you can provide some mock up or sample code.

**Comment by timelyportfolio** [comment]
@sam140 this is my best guess as to what you might be trying to achieve.  See [example](https://beta.observablehq.com/@timelyportfolio/parcoord-es-with-overlay-lines(.

![image](https://user-images.githubusercontent.com/837910/42702366-e59f7146-868e-11e8-80bd-3ed2ed57a20e.png)

**Comment by timelyportfolio** [comment]
The other possibly better approach would be to wait until the axes are drawn and add the horizontal lines to the axes `g` element, so the lines would move along with the axis on reorder.

**Comment by BigFatDog** [comment]
Thank you @timelyportfolio for the demo usage. 
This issue doesn't look like a feature to be implemented. @timelyportfolio 's demo is a good reference to this issue. I want to make a `Gallery` section in readme to link those useful demos later.

However, @sam140, if you find an api of parcoords is insufficient or inconvenient to use when you add overly on parcoords, please tell me. I'll see what I can do.

**Comment by timelyportfolio** [comment]
@BigFatDog ok to close this one?

**Comment by BigFatDog** [comment]
Sure.

**Comment by BigFatDog** [comment]
This issue is closed because @timelyportfolio has already provided an example.
