### ISSUE TITLE
Brush not appearing on axes which have string values?

### ISSUE THREAD

**Issue by ManiacalAce** [BigFatDog/parcoords-es#3]
Also tried on the 'reddit' example in the included demo folder.

Whenever there's a string axis, the brush doesn't appear and stuff is not filterable.
This feature works on the original parcoords.

Can this be fixed?
Were there heavy modifications in this fork?

**Comment by BigFatDog** [comment]
I'll look into this issue and fix it. It may take me around a week to do it.

Yes, there are a lot of modifications due to D3 V4's breaking changes.

**Comment by BigFatDog** [comment]
Hello!
Bugs have been resolved. Please upgrade to v1.0.2. Reddit sample works, too.

**Comment by ManiacalAce** [comment]
Nice! I'll check and revert back. Thanks for the fix.
At the moment I've had to proceed with the original lib.

**Comment by ManiacalAce** [comment]
I tried with the latest changes and things seem to be ok.

Using this lib now instead of original. Had some issues with configuring dimensions in original which doesn't seem to have issues here.

Thanks again for the fix. Here's hoping things go smoothly.
