### ISSUE TITLE
flipAxisAndUpdatePCP() broken

### ISSUE THREAD

**Issue by joshhjacobson** [BigFatDog/parcoords-es#30]
Hi, 

I believe this is a minor bug. When you double click the axis title to flip an axis, the polylines will update but the axis itself does not. The console gives: `TypeError: brushes[d].event is not a function
brushReset.js:24:10`

Very best,
Josh

**Comment by BigFatDog** [comment]
Reproduced. When double click to flip an axis, there is also another minor bug:
```
pc.renderMarkedDefault(); is not a function
```
Will be fixed together.

**Comment by BigFatDog** [comment]
[v2.1.7](https://github.com/BigFatDog/parcoords-es/releases/tag/v2.1.7) has been released with the bugfix
