### ISSUE TITLE
Shuffling/ Reordering axis in progressive rendering parallel coordinate d3 V4?

### ISSUE THREAD

**Issue by Abhijeet-Das** [BigFatDog/parcoords-es#39]
Hello, 

I have been referring to https://bl.ocks.org/syntagmatic/482706e0638c67836d94b20f0cb37122
for progressive rendering in parallel coordinate d3 v4. Do we have an example where we can reorder the axis; like drag and put the axis from one end to other.

Any help or suggested examples will be highly appreciated.
Thanks

**Comment by BigFatDog** [comment]
Hi Abhijeet,
[brushing.html](https://github.com/BigFatDog/parcoords-es/blob/master/demo/brushing.html) shows the usage of reordering.

To make a parcoords reorder-able (this code is from brushing.html):
```
      d3.csv('data/cars.csv').then(function(data) {
            parcoords
                .data(data)
                .hideAxis(["name"])
                .composite("darker")
                .render()
                .shadows()
                .reorderable() // make parcoords reorderable
                .brushMode("1D-axes");  // enable brushing
```
Is this what you are looking for?

**Comment by Abhijeet-Das** [comment]
Hello, 
Thanks for your prompt reply. 
Yes exactly like that, but since I was referring to simpler progressive rendering like that https://bl.ocks.org/syntagmatic/482706e0638c67836d94b20f0cb37122
So I was wondering is there an option to add reorder/shuffle axis code to this. Would you suggest any method that I can directly apply in order to get axis shuffling !

Thanks again for your time.

**Comment by BigFatDog** [comment]
You're welcome!

I'm confused. Are you asking how to reorder axes in the chart that you provided?
Or requesting a feature that should be implemented in `parcoords-es`?

Both progressive rendering and reorder functions are supported by `parcoords-es` and can be enabled in the same chart.

**Comment by Abhijeet-Das** [comment]
Hello , 

Yes, I was actually asking how to reorder the axes in the chart provided. Sorry if my question created confusion. 

Thanks and Regards

**Comment by BigFatDog** [comment]
Never mind. The original parallel coordinates does have [`reorderable` api](https://github.com/syntagmatic/parallel-coordinates#parcoords_reorderable)

**Comment by BigFatDog** [comment]
closed due to inactivity
