### ISSUE TITLE
Multi brush demo in d3 V4 ?

### ISSUE THREAD

**Issue by Abhijeet-Das** [BigFatDog/parcoords-es#4]
Firstly great work on parallel coordinates with updates on much needed D3 V4. 

I have found a sample parallel coordinate with numerical and string axis in D3 V4 like  this 
http://plnkr.co/edit/dCNuBsaDNBwr7CrAJUBe?p=preview

I am looking to have multiple brush feature on an axis in that example ,something like this http://bl.ocks.org/bollwyvl/8463137 .

So do you have a demo example of multi brush in d3 V4, that may have both numerical and string axis and multi brush enabled on every axis?

Thanks for your time

**Comment by Abhijeet-Das** [comment]
Hello, 
Thanks a lot for your time and expert feedback. I am a newbie to the d3 world , so trying to learn from the working examples, but the version update is sometimes tricky.  I will follow your suggestions to make use of canvas and queue rendering on my parallel coordinate.  And, may be, I will wait for the multi brush library to come in V4. 
Thanks again and I hope to learn and explore more from your examples.

**Comment by BigFatDog** [comment]
Anytime.

**Comment by wvpelt** [comment]
any news on added support for multibrush?

**Comment by BigFatDog** [comment]
This is still a limitation of parcoords-es. I may work on this feature in the next week.

**Comment by wvpelt** [comment]
That would be great! Meanwhile I'll try to find a solution myself. I just stumbled across this: http://bl.ocks.org/ludwigschubert/0236fa8594c4b02711b2606a8f95f605
which seems to be multi brush functionality in d3 v4

**Comment by BigFatDog** [comment]
I'll take a closer look at the link you provided as well as other available samples.
My primary goal is to add multi brush to parccords-es, moreover, it would be ideal to publish a standalone d3-v4 multi-brush  along with fixing this issue.

It's quite interesting that when I don't know how to develop a feature on d3.js (or, feels too difficult to do it), I just wait.  People always make inspiring examples and that's quite helpful.
That's part of the fun of d3 community.

**Comment by ManiacalAce** [comment]
+1 polite nudge for this feature.

**Comment by BigFatDog** [comment]
Done. Please upgrade to v2.0.4 to use 1D multi brushes.

Also please refer to [release notes](https://github.com/BigFatDog/parcoords-es/releases/tag/v2.0.4) for setting brush extent when 1D multi brushes mode is used.
