### ISSUE TITLE
Click on axis to reset brush does't work

### ISSUE THREAD

**Issue by ManiacalAce** [BigFatDog/parcoords-es#5]
Is it possible to match the behaviour of the original pcoords as shown here?
http://syntagmatic.github.io/parallel-coordinates/examples/brushing.html

In the above example, after applying a brush on an axis, if I click somewhere on the axis, the brush and the selection gets reset for that axis

In this version of the lib, it's a bit difficult to use. You can never really clear the brush on a single axis.

**Comment by BigFatDog** [comment]
Hello, fixed. please use version: 1.0.3.

**Comment by ManiacalAce** [comment]
Thanks! Works now :D
