### ISSUE TITLE
bundleDimension requires sylvester

### ISSUE THREAD

**Issue by joshhjacobson** [BigFatDog/parcoords-es#51]
Hi there,

I'd really like to be able to use `pc.bundleDimension()` without having to include `sylvester.js` in my html header. The `vector` function in this library is used for `computeCentroids` and returns ```Uncaught ReferenceError: $V is not defined at computeCentroids``` when `sylvester.js` is not included in the script.

The good news is there is a somewhat new library [sylvester-es6](https://github.com/pithumke/sylvester-es6) which should be compatible with `parcoords-es` and would be a quick fix.

I'd be happy to submit a pull request if you're ok with the dependency. Let me know.

**Comment by BigFatDog** [comment]
Sure, go ahead.

**Comment by BigFatDog** [comment]
Thank you for this feature! 
[v2.2.4](https://github.com/BigFatDog/parcoords-es/releases/tag/v2.2.4) is released
