### ISSUE TITLE
brush.move instead of brush.extent in brushExtents

### ISSUE THREAD

**Issue by timelyportfolio** [BigFatDog/parcoords-es#53]
In #6, a very helpful `brushExtents` method was fixed and provided to the API.  However, when setting brushExtents, I think we should use [`brush.move`](https://github.com/d3/d3-brush#brush_move) instead of [`brush.extents`](https://github.com/d3/d3-brush#brush_extent).  I'm not sure how best to provide a reproducible example, so I recorded the screenshot below.  I will submit a pull.  Thanks.

![parcoords-brush-extents](https://user-images.githubusercontent.com/837910/49845206-62858880-fd8b-11e8-8903-877a0d339d84.gif)

**Comment by timelyportfolio** [comment]
Actually, to fix we only need to comment one line.

**Comment by BigFatDog** [comment]
How about this?
`brushExtents` returns objects with value in the following format:
```
extent, //the current return value of brush.extent
brushRange, // brush selection
dataRange // corresponding data range
```
Code modifications
```
const brushRange = brushSelection(brushNodes[cur]);
acc[cur] = {
          extent: brush.extent(),
          brushRange,
          dataRange: [
            config.dimensions[cur].yscale.invert(brushRange[0]),
            config.dimensions[cur].yscale.invert(brushRange[1]),
          ],
        };
```

**Comment by timelyportfolio** [comment]
@bigfatdog, I like this and will closely match our extra information from brush events (https://github.com/BigFatDog/parcoords-es/pull/44/files).  I am wondering though should we use the same names - `selection` for `dataRange` and `selection (raw)` for `brushRange`.   Also, we will need to use the `invertCategorical` ([lines](https://github.com/BigFatDog/parcoords-es/blob/master/src/brush/1d/brushFor.js#L25-L38)) for categorical scales.  Should we move `invertCategorical` so that it is more generically available since we now have > 1 uses?

Thanks!!!

**Comment by BigFatDog** [comment]
Your point makes sense. Pull request #55 has been created.

**Comment by timelyportfolio** [comment]
@BigFatDog going to close; thanks again
