### ISSUE TITLE
Setting nullValueSeparator causes error

### ISSUE THREAD

**Issue by yluijten** [BigFatDog/parcoords-es#7]
Set the `nullValueSeparator` to `bottom` causes the following error in console:

`ERROR ReferenceError: h is not defined`

It looks like the `height` property is not accessible. Maybe you've forgot to import the heigh utility in `index,js` file.

Any ideas?

**Comment by BigFatDog** [comment]
which version are you using?

**Comment by BigFatDog** [comment]
I just have checked code throughout for the occurrence of *height*, I looks fine.

Please check if you're using the latest version: *2.0.3*. If not, upgrading to *2.0.3* will fix the problem

**Comment by yluijten** [comment]
I was running version 2.0.2. Upgrading to 2.0.3 fixed the problem. Thanks!

**Comment by BigFatDog** [comment]
You're welcome.
