### ISSUE TITLE
Provide a react demo

### ISSUE THREAD

**Issue by BigFatDog** [BigFatDog/parcoords-es#74]
This is from discussion #72 Is it necessary to provide a React version for this library?
_Originally posted by @jvmanke in https://github.com/BigFatDog/parcoords-es/issues/72#issuecomment-526702172_
>Hey @BigFatDog maybe not build a separate library but maybe add some examples using it with react? I personally am struggling to get it working properly. Do you have a snippet I could look?

Need to provide a simple react app that with `parcoords-es`.

**Comment by jvmanke** [comment]
@BigFatDog  I've been working on a react wrapper  in [jvmanke/react-parcoords-es](https://github.com/jvmanke/react-parcoords-es/tree/dev), maybe it can give you some more inspiration on implementation!

**Comment by BigFatDog** [comment]
demo has been provided in `demo/react-app`
