### ISSUE TITLE
ParCoords.dimensions() yscale not working?

### ISSUE THREAD

**Issue by cfrankowski** [BigFatDog/parcoords-es#9]
Changing the scale with .dimension(dimension) is not working for me.

Setting a custom scale with yscale has been removed from the dimensions object in the axis-config example as well.

**Comment by BigFatDog** [comment]
Fixed. v2.0.5 has been released with the bug fix

**Comment by BigFatDog** [comment]
please also refer to [demo/axis-config-2.html](https://github.com/BigFatDog/parcoords-es/blob/master/demo/axis-config-2.html) for to usage.
